### ISSUE TITLE
Client does not work with current version of PyQt4

### ISSUE THREAD

**Issue by pitwegner** [Freenove/Freenove_Three-wheeled_Smart_Car_Kit_for_Raspberry_Pi#1]
The client does not start up with error
```
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    from Ui_main import Ui_MainWindow
  File "/home/pi/Freenove_Three-wheeled_Smart_Car_Kit_for_Raspberry_Pi/Client/Ui_main.py", line 542, in <module>
    from PyQt4 import QtWebKit
ImportError: cannot import name QtWebKit
```
Appearently the latest version of PyQt4 does not include QtWebKit anymore. Do you have any suggestions how to fix this?

**Comment by SuhaylZhao** [comment]
Hi,

The solution to this problem is in file "Patch for Stretch.pdf", Please read it carefully and follow the steps.

Thanks .
