### ISSUE TITLE
auto start server

### ISSUE THREAD

**Issue by tamerin-tech** [Freenove/Freenove_Three-wheeled_Smart_Car_Kit_for_Raspberry_Pi#3]
Hi,
I would like to be able to start the server and the listeners (camera, tcp) automatically.
How can this be done?

**Comment by SuhaylZhao** [comment]
Hi, 

Please look at the 75 page "Automatic Start" in the file "Tutorial.pdf". Then follow the steps to set up the service auto-start.

Thanks.
